<!-- Iterate through associative array and echo out values -->
<div class="post">
    <!-- Link to the individual post page based of its ID -->
    <a href="#">
        <div class="post-header">
            <p>
                <span class="username">
                    <!-- Show username  -->
                </span>
                <span class="date-time">
                    <!-- Date format "Oct 24th, 2017"  -->
                </span>
            </p>
        </div>
        <div class="post-body">
            <p>
                <!-- Show first 200 charatcers of post here -->
                <!-- Concat ellipsis ... to the end if the post is greater -->
                <!-- than 200 characters -->
            </p>
        </div>
    </a>
</div>
